force-app/main/default/objects/Designation__c/Designation__c.object-meta.xml
<CustomObject>
    <description>Designations and title awarded</description>
    <label>Designation</label>
    <nameField>
        <displayFormat>DG-{0000}</displayFormat>
        <label>Designation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Designations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Designation__c/fields/Designation__c.field-meta.xml
<CustomField>
    <fullName>Designation__c</fullName>
    <description>Additional designations the Referee holds with USRowing</description>
    <inlineHelpText>Additional designations the Referee holds with USRowing</inlineHelpText>
    <label>Designation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assistant Referee</fullName>
            </value>
            <value>
                <fullName>Full Referee</fullName>
                <label>Referee</label>
            </value>
            <value>
                <fullName>Chief Referee</fullName>
            </value>
            <value>
                <fullName>Emeritus</fullName>
            </value>
            <value>
                <fullName>FISA</fullName>
            </value>
            <value>
                <fullName>Clinician</fullName>
            </value>
            <value>
                <fullName>Mentor</fullName>
            </value>
            <value>
                <fullName>Referee College Faculty</fullName>
            </value>
            <value>
                <fullName>Referee Committee</fullName>
            </value>
            <value>
                <fullName>Regional Coordinator</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
            </value>
            <value>
                <fullName>Candidate Referee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Designation__c/fields/Designation_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Designation_End_Date__c</fullName>
    <description>End date for the designation. For Clinician Designation, create a new record if there is a gap in service.</description>
    <inlineHelpText>End date for the designation. For Clinician Designation, create a new record if there is a gap in service.</inlineHelpText>
    <label>Designation End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Designation__c/fields/Designation_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Designation_Start_Date__c</fullName>
    <description>Date designation was recorded</description>
    <inlineHelpText>Date designation was recorded</inlineHelpText>
    <label>Designation Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Designation__c/fields/Designee__c.field-meta.xml
<CustomField>
    <fullName>Designee__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Person awarded the designation</description>
    <inlineHelpText>Person awarded the designation</inlineHelpText>
    <label>Designee</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Designations</relationshipLabel>
    <relationshipName>Designations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Designation__c/fields/Designee_User__c.field-meta.xml
<CustomField>
    <fullName>Designee_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Person awarded the designation</description>
    <inlineHelpText>Person awarded the designation</inlineHelpText>
    <label>Designee User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Designations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DesignationController.cls
public with sharing class DesignationController {

    @AuraEnabled 
    public static List<Designation__c> fetchContactDesignations(String pDesigneeId) {
        String pExclusionList =  null;  //'Full Referee,Assistant Referee,Candidate Referee';
        return fetchContactDesignations(pDesigneeId,pExclusionList);
    }

    @AuraEnabled 
    public static List<Designation__c> fetchContactDesignations(String pDesigneeId, String pExclusionList ){

        /* THIS IS A FULL DATA PULL JOINING Designation__c and Contact
            select Name, designee__r.name, designee_user__c, designee__c,
            designee__r.referee_rank__c, 
            designee__r.referee_status__c, isdeleted,
            designation__c, Designation_Start_Date__c,
            Designation_End_Date__c
            from Designation__c
            where designee__c =: Designee
            order by designation_start_date__c desc
			
		   THIS IS THE TEST SELECT
			Contact ContactData = [select name, id from contact where referee_rank__c = 'Referee' and 
				id in (select designee__c from designation__c) limit 1];
        */

        System.debug(LoggingLevel.DEBUG, 'DesignationController.fetchContactDesignations pDesigneeId=' + pDesigneeId + ' pExclusionList=' + pExclusionList );

        /*  Dropped this select so I could implement a more dynamic select with an exclusion list
        List<Designation__c> designations = [select Id, 
            Name, 
            designee__c,
            designation__c, 
            Designation_Start_Date__c, 
            Designation_End_Date__c
            from Designation__c 
            where designee__c =: pDesigneeId
            and IsDeleted = false
            order by Designation_Start_Date__c desc, Name desc];
        */
        String searchquery = 'select Id, Name, designee__c, designation__c, Designation_Start_Date__c,  Designation_End_Date__c from Designation__c ';
        searchquery = searchquery + 'where designee__c = \'' + pDesigneeId + '\' and IsDeleted = false ';
        if(!String.isBlank(pExclusionList)) {
            searchquery = searchquery + ' and designation__c not in ' + pExclusionList +  ' ';
        }
        searchquery = searchquery + 'order by Designation_Start_Date__c desc, Name desc';

        System.debug(LoggingLevel.DEBUG, 'DesignationController.fetchContactDesignations: ' + searchquery);

        List<Designation__c> designations = Database.query(searchquery);

        System.debug(LoggingLevel.DEBUG, 'In DesignationController.fetchContactDesignations returning ' + designations.size() + ' records' );
        
        return designations;
    }
        
    @AuraEnabled 
    public static List<String> getDesignationsPicklist() {
        List<String> designationpicklist = new List<String>();
        Schema.DescribeFieldResult designationPL = Designation__c.Designation__c.getDescribe();
		List<Schema.PicklistEntry> picklist = designationPL.getPicklistValues();
        for(Schema.PicklistEntry entry : picklist) {
            System.debug(LoggingLevel.DEBUG, 'In DesignationController.fetchContactDesignations entry.getValue() = ' + entry.getValue());
            designationpicklist.add(entry.getValue());
        }
        return designationpicklist;    
    }
        
}