force-app/main/default/objects/Designation__c/Designation__c.object-meta.xml
<CustomObject>
    <description>Designations and title awarded</description>
    <label>Designation</label>
    <nameField>
        <displayFormat>DG-{0000}</displayFormat>
        <label>Designation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Designations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Designation__c/fields/Designation__c.field-meta.xml
<CustomField>
    <fullName>Designation__c</fullName>
    <description>Additional designations the Referee holds with USRowing</description>
    <inlineHelpText>Additional designations the Referee holds with USRowing</inlineHelpText>
    <label>Designation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assistant Referee</fullName>
            </value>
            <value>
                <fullName>Full Referee</fullName>
                <label>Referee</label>
            </value>
            <value>
                <fullName>Chief Referee</fullName>
            </value>
            <value>
                <fullName>Emeritus</fullName>
            </value>
            <value>
                <fullName>FISA</fullName>
            </value>
            <value>
                <fullName>Clinician</fullName>
            </value>
            <value>
                <fullName>Mentor</fullName>
            </value>
            <value>
                <fullName>Referee College Faculty</fullName>
            </value>
            <value>
                <fullName>Referee Committee</fullName>
            </value>
            <value>
                <fullName>Regional Coordinator</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
            </value>
            <value>
                <fullName>Candidate Referee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DesignationControllerTest.cls
@IsTest
public with sharing class DesignationControllerTest {

    @IsTest(SeeAllData=true) 
    public static void testFetchContactDesignations() {

        System.debug('testFetchContactDesignations Confirm appropriate list returned');
        Exception unexpectedException;
        try {

            Contact ContactData = [SELECT Id from Contact where Referee_Rank__c = 'Referee' limit 1];

            System.debug('ContactId = ' + ContactData.Id);

            List<Designation__c> designations = DesignationController.fetchContactDesignations(ContactData.Id);
        
            System.assert( designations != null,'testFetchContactDesignations - A list was not returned');

        } catch (Exception err) {
            System.debug('testFetchContactDesignations err: ' + err);
            unexpectedException = err;
        }    
        system.assertEquals(null, unexpectedException, 'testFetchContactDesignations unexpected Exception');
        System.debug('testFetchContactDesignations completed');

    }
}